import { User } from '../../domain/entities/User';
import { AuthRepository } from '../../domain/repositories/AuthRepository';
import { UserModel, toUser } from '../models/UserModel';
import mockApi from '../services/ApiService';

export class AuthRepositoryImpl implements AuthRepository {
  async login(email: string, password: string): Promise<User> {
    console.log('Logging in with', email, password);
    if (email === 'aplicacio@gmail.com' && password === '12345') {
      const mockUser: UserModel = {
        id: '1',
        email,
        role: 'student',
        firstName: 'Test',
        lastName: 'User',
      };
      const response = await mockApi(mockUser);
      return toUser(response);
    } else if (email === 'cafeteria@gmail.com' && password === '12345') {
      const mockUser: UserModel = {
        id: '3',
        email,
        role: 'cafeteria',
        firstName: 'Admin',
        lastName: 'User',
      };
      const response = await mockApi(mockUser);
      return toUser(response);
    } else if (email === 'parent@gmail.com' && password === '12345') {
      const mockUser: UserModel = {
        id: '4',
        email,
        role: 'parent',
        firstName: 'Parent',
        lastName: 'User',
        childId: 'student1',
      };
      const response = await mockApi(mockUser);
      return toUser(response);
    }
    throw new Error('Invalid credentials');
  }

  async register(userData: Omit<User, 'id'> & { password: string }): Promise<User> {
    console.log('Registering user', userData);
    const { password, ...userWithoutPassword } = userData;
    const mockUser: UserModel = {
      id: '2', // In a real app, the ID would be generated by the backend.
      ...userWithoutPassword,
    };
    const response = await mockApi(mockUser);
    return toUser(response);
  }

  async logout(): Promise<void> {
    console.log('Logging out');
    await mockApi(null);
  }

  async getCurrentUser(): Promise<User | null> {
    console.log('Getting current user');
    // In a real app, you'd check for a stored token and validate it with the backend.
    const response = await mockApi(null);
    return response;
  }
}
